### ISSUE TITLE
version of tf mismatch?

### ISSUE THREAD

**Issue by minoriwww** [YJango/tensorflow#1]
I used r0.12, ran RNN_v2 and errors occured in 'concat' and 'reverse' methods.
Then I turned to doc, and found this:
https://www.tensorflow.org/versions/r0.12/api_docs/python/array_ops/slicing_and_joining#concat
https://www.tensorflow.org/versions/r0.12/api_docs/python/array_ops/slicing_and_joining#concat_v2
so I should use concat_v2 instead.
but in version 0.11 as you mention in README. it do not have an parameter named "axis"
https://www.tensorflow.org/versions/r0.11/api_docs/python/array_ops/slicing_and_joining#concat

In r1.0, TF replaced concat_v2 with concat, also reverse...So what version are you using now? :P

**Comment by YJango** [comment]
The lstm gru code was tested with Tensorflow r1.0


Yu

**Comment by YJango** [comment]
In r0.12, 
change to the following code
tf.concat--->"tf.concat(values=[self.igate[0], self.fgate[0], self.ogate[0], self.cell[0]], concat_dim=1)"
tf.stack and tf.unstack--->"tf.pack" and "tf.unpack"
tf.reverse--->tf.reverse(cell.incoming, [True,False,False])
